@startuml Sequence mode auto

skinparam SequenceGroupBodyBackgroundColor #FFFFFF90
skinparam SequenceMessageAlign reverseDirection

actor user order 1

box "ZYBO" #LightBlue
    participant tcp_server_rcv as server_rcv order 4
    participant tcp_server_send as server_send order 5
    participant interpreteur as int order 6
    participant demo.sh as script order 7
    participant process_IA as ia order 8
    participant preprocess as pr order 9
end box

box "station sol" #MistyRose
    participant ihm as ihm order 2
    participant tcp_client as client order 3
end box

activate server_rcv
user -> ihm : Mode auto
ihm -> client : TC mode auto
client -> server_rcv : TCP frame
server_rcv -> int : struct update
int -> server_send : ACK 
activate server_send
server_send -> client : ACK
deactivate server_send
client -> ihm : log
    group while auto
        int -> script : bash demo.sh
        activate script 
        note over script #LightSalmon:  update temp.bmp \n with  random img \n from dataset
        script -> ia : SIGUSR1
        deactivate script
        activate ia 
        ia -> pr : preprocess()
        activate pr 
        note over pr #LightSalmon : update temp.csv 
        ' pr -> pr : update temp.csv
        pr -> ia
        deactivate pr 
        ia -> int : IAtoINT_pipe(prediction)
        deactivate ia
        int -> server_send : process img_f
        group if (img_f == true)
            activate server_send
            server_send -> client : send image
            deactivate server_send
        end
    end
    client -> ihm : visionneuse
@enduml